"""add_placement

Revision ID: 1fc0801f3865
Revises: 313ee826b8ec
Create Date: 2026-01-03 02:00:03.326721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1fc0801f3865'
down_revision: Union[str, Sequence[str], None] = '313ee826b8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchparticipation', sa.Column('position', sa.Integer(), nullable=False,server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchparticipation', 'position')
    # ### end Alembic commands ###
