"""initial_fresh_start

Revision ID: 2f596de68a61
Revises: 
Create Date: 2026-01-11 02:01:44.706523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f596de68a61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('displayName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('displayIcon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('map_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('start_time_patched', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('winning_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rounds_play', sa.Integer(), nullable=False),
    sa.Column('blue_team_score', sa.Integer(), nullable=False),
    sa.Column('red_team_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=True)
    op.create_table('user',
    sa.Column('puuid', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_index(op.f('ix_user_puuid'), 'user', ['puuid'], unique=True)
    op.create_table('matchparticipation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('map', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('puuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('combat_score', sa.Integer(), nullable=False),
    sa.Column('headshots', sa.Integer(), nullable=False),
    sa.Column('othershots', sa.Integer(), nullable=False),
    sa.Column('damage_dealt', sa.Integer(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.Column('roundsWon', sa.Integer(), nullable=False),
    sa.Column('roundsLost', sa.Integer(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('linked_to_match', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchparticipation_match_id'), 'matchparticipation', ['match_id'], unique=False)
    op.create_index(op.f('ix_matchparticipation_puuid'), 'matchparticipation', ['puuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matchparticipation_puuid'), table_name='matchparticipation')
    op.drop_index(op.f('ix_matchparticipation_match_id'), table_name='matchparticipation')
    op.drop_table('matchparticipation')
    op.drop_index(op.f('ix_user_puuid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_table('match')
    op.drop_table('agent')
    # ### end Alembic commands ###
