"""added_headshot_percent

Revision ID: 313ee826b8ec
Revises: 4d40463c7dc5
Create Date: 2026-01-03 00:57:35.163054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import  sqlmodel


# revision identifiers, used by Alembic.
revision: str = '313ee826b8ec'
down_revision: Union[str, Sequence[str], None] = '4d40463c7dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('blue_team_score', sa.Integer(), nullable=False,server_default="0"))
    op.add_column('match', sa.Column('red_team_score', sa.Integer(), nullable=False,server_default="0"))
    op.add_column('matchparticipation', sa.Column('roundsWon', sa.Integer(), nullable=False,server_default="0"))
    op.add_column('matchparticipation', sa.Column('roundsLost', sa.Integer(), nullable=False,server_default="0"))
    op.add_column('matchparticipation', sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False,server_default="unknown"))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchparticipation', 'result')
    op.drop_column('matchparticipation', 'roundsLost')
    op.drop_column('matchparticipation', 'roundsWon')
    op.drop_column('match', 'red_team_score')
    op.drop_column('match', 'blue_team_score')
    # ### end Alembic commands ###
