"""add current rank image

Revision ID: f652df4f8886
Revises: e1dd0579c919
Create Date: 2026-02-10 04:13:41.972738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f652df4f8886'
down_revision: Union[str, Sequence[str], None] = 'e1dd0579c919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchparticipation', sa.Column('current_rank_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchparticipation', 'current_rank_image')
    # ### end Alembic commands ###
